title: "MW122 - Topics in Econometrics and Data Science   "
description: "Prof. Dr. Jannis Kück, Alexandra Gibbon (M.Sc.), Mara Mattes (M.Sc.)"

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

